spring:
  application:
    name: api-service
  profiles:
    active:
    - ${AMBIENTE:prod}

server:
  port: 9892

wavefront:
  application:
   name: console-availability

management:
  wavefront:
    source: my-cloud-server
