spring:
  application:
    name: api-service
  profiles:
    active:
    - ${AMBIENTE:prod}
  devtools:
    add-properties: true
  sleuth:
    jdbc:
      p6spy:
        enable-logging: true

server:
  port: ${PORT:9892}
  compression:
      enabled: true
      min-response-size: 1

management:
  wavefront:
    application:
      name: console-availability-daniel
      service: availability-service
    source: daniel-spring-cloud-server-metric
    api-token: b2df6c19-b00e-4f3c-87ce-ac1ee74bab63
    uri: https://wavefront.surf
  tracing:
    sampling:
      probability: 1.0