spring:
  application:
    name: api-client
  profiles:
    active:
    - ${AMBIENTE:prod}
  devtools:
    add-properties: true
  sleuth:
    jdbc:
      p6spy:
        enable-logging: true

server:
  port: ${PORT:9891}
  compression:
      enabled: true
      min-response-size: 1

management:
  wavefront:
    application:
      name: console-availability-daniel
      service: availability-client
    source: daniel-spring-cloud-server-metric
    api-token: b2df6c19-b00e-4f3c-87ce-ac1ee74bab63
    uri: https://wavefront.surf

availability:
  client:
    url: ${CLIENT_URL:http://localhost:9892}
    path: ${PATH_API:/availability/{console}}